### ISSUE TITLE
Add Github Pages

### ISSUE THREAD

**Issue by clupasq** [Siderite/WordsAlive.js#2]
Hi!

Just noticed your project includes a _sample.html_ file. You could expose that via the [Github Pages mechanism](https://pages.github.com/).

To do it, simply create a new branch called `gh-pages` off of your current `master` branch.

In my fork of the repo I did that, and voila: http://wolfascu.github.io/WordsAlive.js/sample.html.

I cannot, however open a pull request, since there is no `gh-pages` branch to pull into in the original repo. If you decide to do this change, the file will be visible at the url: http://siderite.github.io/WordsAlive.js/sample.html (though it could take a few minutes to appear).

Thanks for this project and for the things you post on your blog!

**Comment by Siderite** [comment]
Thank you! Forgive my feeble efforts in the GitHub world: I just joined :)
